Repository HIT-OS/VN_Legal_Document_Retrieval, pull requests merged in 2024-11, with the labels that each got.

#5 feat: initialize server service and authentication setup #3
  server/.env.example
  server/.eslintrc.js
  server/.gitignore
  server/.prettierignore
  server/.prettierrc
  server/README.md
  server/nest-cli.json
  server/package.json
  server/prisma/migrations/20241115152026_user/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
  server/src/app.module.ts
  server/src/application/application.module.ts
  server/src/application/command/auth/handler/index.ts
  server/src/application/command/auth/handler/login.handler.ts
  server/src/application/command/auth/handler/register.handler.ts
  server/src/application/command/auth/interface/index.ts
  server/src/application/command/auth/interface/login.command.ts
  server/src/application/command/auth/interface/register.command.ts
  server/src/application/command/index.ts
  server/src/application/dto/request/auth/login.dto.ts
  server/src/application/dto/request/auth/register.dto.ts
  server/src/common/constants/auth.constant.ts
  server/src/common/constants/index.ts
  server/src/common/interceptors/error.interceptor.ts
  server/src/common/interceptors/response.interceptor.ts
  server/src/domain/guards/auth.guard.ts
  server/src/domain/repositories/user.repository.interface.ts
  server/src/infrastructure/config/app.config.ts
  server/src/infrastructure/config/database.config.ts
  server/src/infrastructure/controllers/auth.controller.ts
  server/src/infrastructure/controllers/index.ts
  server/src/infrastructure/controllers/question.controller.ts
  server/src/infrastructure/controllers/user.controller.ts
  server/src/infrastructure/infrastructure.module.ts
  server/src/infrastructure/providers/index.ts
  server/src/infrastructure/providers/user.repository.provider.ts
  server/src/infrastructure/repositories/user.prisma.repository.ts
  server/src/infrastructure/services/jwt.config.service.ts
  server/src/infrastructure/services/prisma.service.ts
  server/src/main.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.build.json
  server/tsconfig.json
  server/yarn.lock
Labels: enhancement

#8 refactor: add license to all file
  law-crawler/db.py
  law-crawler/document-crawler/main.py
  law-crawler/document-crawler/split_document.py
  law-crawler/helper.py
  law-crawler/main.py
  law-crawler/models/models.py
Labels: license

#15 feat/rag
  rag/.dockerignore
  rag/.gitignore
  rag/Dockerfile
  rag/README.md
  rag/app.py
  rag/cache.py
  rag/data/process.py
  rag/directory.py
  rag/image/qa.png
  rag/image/rag_flow.png
  rag/models.py
  rag/requirements.txt
  rag/vectorize_corpus.py
Labels: model
